### ISSUE TITLE
curl error

### ISSUE THREAD

**Issue by itchefk0ch** [psiri/letsencrypt_paloalto#2]
i ran pan_certbot as root and get the following error message:

**curl: (3) URL using bad/illegal format or missing URL**

i controlled all my inputs for pan_cerbot several times. can't find any mistakes :/
I use latest ubuntu server with all updates. clean installation.
PAN OS Version:  11.0.2 / VM-Series based on Microsoft Hyper-V

**Comment by psiri** [comment]
Hi @itchefk0ch 

> **curl: (3) URL using bad/illegal format or missing URL**

- This looks to be an issue with one or more parts of the URL passed by the script when interacting with the firewall.  
- Most common causes here would be invalid characters - likely from one or more of the input variables (since that's really the only difference between any API calls for this functionality:

    1. Can you confirm that you did not modify the default behavior (generating a temporary password)?
        - If you did modify this (or hard-code a password), you will need to ensure that the characters are all valid when passed as a URL. The easiest way to rule this out is to create a temp/dummy password using only letters and numbers, and re-attempt.
        - Special characters are typically the culprit `@`, `$`,  space, etc.  If necessary [they can be URL-encoded](https://www.w3schools.com/tags/ref_urlencode.ASP)
     2. What is the value you're passing for `CERT_NAME`? This would also need to follow the same logic as (1)
     3. What is the value you're passing for `GP_PORTAL_TLS_PROFILE` and `GP_GW_TLS_PROFILE`? This would also need to follow the same logic as (1)
     4. Can you confirm you used an IP address in the `PAN_MGMT` variable, and that it's reachable from the server?
         - A FQDN is also acceptable. In this case you'd also need to confirm the host can resolve the DNS name of the FW 


> i controlled all my inputs for pan_cerbot several times. can't find any mistakes :/ I use latest ubuntu server with all updates. clean installation. PAN OS Version: 11.0.2 / VM-Series based on Microsoft Hyper-V

- This script has been validated against PAN-OS 8 - 11 (11.0.1 and 11.0.2), and apart from the one corner case mentioned below, no issues or changes to API path required (Panorama will require API path change though). 
    - There can potentially be issues with replacing the cert if it is currently stored in both the "shared" device configuration as well as one or more of the VSYS configs.  If you discover this is the case, then you'll need to remove the cert from the VSYS config(s) before you can properly upload and reference it from the "shared" config.  This is not likely to be your issue though based on the error.

**Comment by itchefk0ch** [comment]
thank your for your super fast reply. 
i think i have a problem with the api key and the .panrc file.
if i paste the complete api key into the pan_certbot file it will work for me.

**Comment by psiri** [comment]
> i think i have a problem with the api key and the .panrc file. if i paste the complete api key into the pan_certbot file it will work for me.

- it isn't explicitly mentioned in the notes, but the  `.panrc` file must be accessible by the user running cron (or manually executing the script while testing). 
- The `.panrc` file should only contian the API key with no extra whitespace, etc. Ex: `cat .panrc` produces:
    - `LUXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXRA==`
- Were you signed-in as the same user when you executed `panxapi.py -h PAN_MGMT_IP_OR_FQDN -l USERNAME:'PASSWORD' -k >> ~/.panrc` to generate the API key?  If not, the `.panrc` file may have been stored in a different home dir.
    - If you ran that as root for example, it might be located at `/root/.panrc` which would not be accessible to your "normal" user by default
    - Same would be true for the file permissions - user running cron (or manually executing the script while testing) must be able to read the `.panrc` file
- The `API_KEY=$(cat FULL_PATH_TO/.panrc)` line needs to contain the full directory path to the `.panrc` file
    - If you're in the same directory where the `.panrc` file lives, just issue `pwd` and replace `FULL_PATH_TO` with the results
        - If `pwd` produced `/home/psiri`, then the value should be  `API_KEY=$(cat /home/psiri/.panrc)`

**Comment by psiri** [comment]
@itchefk0ch - were you able to resolve your issue with the API Key and successfully run the script?
If so I will close this issue and update the readme with additional troubleshooting docs based on this thread
